
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Resultado;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Sexo;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Eleccion;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Partido;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Municipio;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Departamento;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Region;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Pais;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.temporal;
DROP TABLE IF EXISTS `DATAWAREHOUSE`.Raza;

DROP TABLE IF EXISTS `DatamartPoblacion`.Resultado;
DROP TABLE IF EXISTS `DatamartPoblacion`.Partido;
DROP TABLE IF EXISTS `DatamartPoblacion`.Raza;


DROP TABLE IF EXISTS `DatamartPartidos`.resul_de_partidos_por_region;